export const GET_ALBUMS = 'GET_ALBUMS'
export const GET_ALBUM = 'GET_ALBUM'
export const GET_PHOTOS = 'GET_PHOTOS'
export const GET_PHOTO = 'GET_PHOTO'
export const CLEAR_ = 'CLEAR_'
export const SET_LOADING = 'SET_LOADING'